### ISSUE TITLE
About per-pixel noise

### ISSUE THREAD

**Issue by jychoi118** [yalharbi/StructuredNoiseInjection#2]
I'm curious why the  model **without per-pixel noise** is used in table 1 in the paper.

Per-pixel noise seems to be effective to disentanglement according to the table2 and original StyleGAN literature. And this code is currently enabling per-pixel noise.

**Comment by yalharbi** [comment]
It is only an issue of time. Training the full resolution model takes weeks. After realizing that the per-pixel noise is important (by producing the lower resolution table2), we did not have enough time to retrain the full model with per-pixel noise.

We did find that per-pixel noise is important for both quality (FID) and disentanglement (linear separability and path length).

**Comment by yalharbi** [comment]
While we were formulating the idea we imagined that per-pixel noise might have a negative effect (because it distorts the spatial correspondence by adding spatially-variable noise). This is why we avoided it in the beginning.

But we found that it doesn't affect our spatial disentanglement, and it improves scores.

**Comment by jychoi118** [comment]
Thank you very much :)
